server:
  port: 8080
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: IAM-SERVICE
          uri: http://ec2-18-212-53-8.compute-1.amazonaws.com:9091
          predicates:
            - Path=/v1.0/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: IAM-SERVICE
                fallbackuri: forward:/fallback/breaker
        - id: MASTER-SERVICE
          uri: http://ec2-18-212-64-146.compute-1.amazonaws.com:9090
          predicates:
            - Path=/question/**
          filters:
            - name: CircuitBreaker
              args:
                name: MASTER-SERVICE
                fallbackuri: forward:/fallback/breaker




